on-join-commands:
- horizon verbose
- grim verbose
experimental-features: true
join-message: '&l&7%player%!!!!!! &l&7Welcome &l&4Rebugger&l&7'
delete-player-config-after-loading: false
allow-sub-commands: true
potion-settings-max-timer: 3600
potion-settings-max-level: 127
rebug-scoreboard: true
scoreboard-title: '&l&7killstorm103''s&r'
proximity-player-hider: 5.1
client-info-grab-fail: warn
allow-overriding-client-brand: true
antiexploit-override-client-brand: warn
anti-cancel-client-brand-packet: true
anti-cancel-client-brand-counter: 250
tell-client-info-on-join: true
tell-client-registers: true
cancel-weather-changes: true
force-gamemode-on-join: true
map-version: v1.1
discord-link: https://invite.gg/mhecommunity
server-rules:
- No Doxing/Leaking info
- No Dossing other players or the server
- No Griefing
- No Spamming
- No Scamming
- Don't be an uptight prick
- Niggers a nigger a whore's whore a faggots a faggot women don't have dicks there's only 2 genders etc i COULDN'T GiVE A FUCK if someone states a fact so don't come to me over this stuff wanting me to mute/kick/ban them!
user-update-perms-command: lp user %user% parent set %anticheat%
