ConsoleFilter:
  enabled: true
  blocked:
  - was kicked for floating too long!
  - moved wrongly!
  - now inherits permissions from
  - had their existing parent groups cleared, and now only inherits
  - You are also running NoCheatPlus!
  - NoCheatPlus has been known to conflict with AntiCheat's results and create false cheat detections.
  - Please remove or disable NoCheatPlus to silence this warning.
  - No new version available
  - No blocks filled
  - group (none) is not in sorting list! Sorting list
  - Registered check
  - 'lost connection: Flying is not enabled on this server'
  - logged in with entity id
  - handleDisconnection() called twice
  - Another command is being executed, waiting for it to finish...
  - moved too quickly!
  - 'have a high latency. Count:'
  - failed
  - was punished for
  - 'lost connection: Disconnected'
  - You are currently using free(trial) version of Matrix!
are-users-allowed-to-disable-kicks: true
on-join-commands:
  everytime:
  - grim verbose
  - foxaddition verbose
  - matrix verbose
  once:
  - horizon verbose
client-command-checker:
  blockCommands: true
  sendOnce: false
  topString: '&e------&aplease click the button&e------'
  bottomString: '&e------&aplease click the button&e------'
experimental-feature-warning: true
experimental-features:
- show title
- nofall water bucket
max-vclip-value: 1000
infinite-blocks-enabled: true
special-tnt-enabled: true
special-tnt-fuseticks: 71
join-message: '&l&7%player%!!!!!! &l&7Welcome &l&4Rebugger&l&7'
delete-player-config-after-loading: false
allow-sub-commands: true
potion-settings-max-timer: 3600
potion-settings-max-level: 127
rebug-scoreboard: true
scoreboard-title: '&l&7killstorm103''s&r'
proximity-player-hider: 5.1
client-info-grab-fail: warn
allow-overriding-client-brand: true
antiexploit-override-client-brand: warn
anti-cancel-client-brand-packet: true
anti-cancel-client-brand-counter: 250
tell-client-info-on-join: true
tell-client-registers: true
cancel-weather-changes: true
force-gamemode-on-join: true
auto-refill-blocks-ticks: 200
map-version: v1.1
discord-link: https://invite.gg/mhecommunity
server-rules:
- No Doxing/Leaking info
- No Dossing other players or the server
- No Griefing
- No Spamming
- No Scamming
- Don't be an uptight prick
- Niggers a nigger a whore's whore a faggots a faggot women don't have dicks there's only 2 genders etc i COULDN'T GiVE A FUCK if someone states a fact so don't come to me over this stuff wanting me to mute/kick/ban them!
user-update-perms-command: lp user %user% parent set %anticheat%
use-ranks: true
use-one-rank: true
user-staff-group-command: lp user %user% parent add
is-clear-lag-plugin-enabled: true
clear-lag-command: lagg clear
cancel-explosions-break-blocks: false
AlwaysAllowedToBuild: false
scaffold-test-area:
  minX: 3
  minY: 52
  minZ: 222
  maxX: 61
  maxY: 255
  maxZ: 302
  auto-clear: true
  clear_blocks_command: fill
world-spawn:
  use-this: true
  set-rots: true
  posX: 41
  posY: 58
  posZ: 319
  Yaw: -91.200165
  Pitch: -0.5999501
events:
  packetevents:
    PacketSendEvent: true
    PacketReceiveEvent: true
  bukkit:
    PlayerJoinEvent: true
    PlayerQuitEvent: true
    PlayerKickEvent: true
    PlayerMoveEvent: true
    PlayerDeathEvent: true
    PlayerRespawnEvent: true
    PlayerChangedWorldEvent: true
    FoodLevelChangeEvent: true
    AsyncPlayerChatEvent: true
    EnchantItemEvent: false
    EntityDamageEvent: true
    EntityExplodeEvent: true
    EntityShootBowEvent: true
    ProjectileHitEvent: true
    BlockPlaceEvent: true
    BlockBreakEvent: true
    InventoryClickEvent: true
    InventoryDragEvent: true
    WeatherChangeEvent: false
stop-enchanting-and-anvil-use: false
enchanting-and-anvil-use-permission: me.killstorm103.rebug.user.enchant_anvil
