## Player Settings
Hide Online Players: false
Proximity Player Hider: false
Notify Flying Kick 1.8.x: true
Notify Flying Kick 1.9: false
Vanilla 1.9 fly Check: true
Vanilla 1.8.x fly Check: true
Fire Resistance: false
Damage Resistance: false
Hunger: false
Exterranl Damage: true
Fall Damage: true
Auto Close AntiCheat Menu: true
AntiCheat Kick: false
Show Flags: true
Show Punishes: true
Show Setbacks: true
Allow Direct Messages: true
Allow Potion Effects: true
Auto Refill Blocks Placed: false
Allow Mentions: true
Infinite Blocks: false
Yapper: 0
S08 Alerts: true
## PacketDebugger Settings
Flying: true
Position: true
PositionLook: true
Look: true
Arm Animation: true
Held Item Slot: true
Digging: true
Block Place: true
Entity Action: true
Close Window: true
Click Window: true
Client Settings: true
Client Status: true
Abilities: true
Keep Alive: true
Transaction: true
Spectate: true
Steer Vehicle: true
Custom PayLoad: true
Tab Complete: true
