name: Rebug
version: 1.7
main: me.killstorm103.Rebug.Main.Rebug
author: killstorm103
description: REBUG is a Test Server Plugin that allows you to switch between different AntiCheats and allows users to test exploits on players clients
commands:
  rebug:
    description: command prefix for using rebugs commands
    usage: rebug <command>
  client:
    description: Gets the client brand of a player!
    usage: /<command>
    permissions:
    - me.killstorm103.rebug.command.client
    - me.killstorm103.rebug.*
    - me.killstorm103.rebug.server_owner
    - me.killstorm103.rebug.server_admin
    - me.killstorm103.rebug.commands.*
  exploits:
    description: Opens exploits menu!
    usage: /<command>
    permissions:
    - me.killstorm103.rebug.command.menu
    - me.killstorm103.rebug.user.use_exploits
    - me.killstorm103.rebug.*
    - me.killstorm103.rebug.server_owner
    - me.killstorm103.rebug.server_admin
    - me.killstorm103.rebug.commands.*
  credits:
    description: Opens exploits menu!
    usage: /<command>
    permissions:
    - me.killstorm103.rebug.command.creditscmd
    - me.killstorm103.rebug.*
    - me.killstorm103.rebug.server_owner
    - me.killstorm103.rebug.server_admin
    - me.killstorm103.rebug.commands.*
  crashers:
    description: Opens crashers menu!
    usage: /<command>
    permissions:
    - me.killstorm103.rebug.command.menu
    - me.killstorm103.rebug.user.use_crashers
    - me.killstorm103.rebug.*
    - me.killstorm103.rebug.server_owner
    - me.killstorm103.rebug.server_admin
    - me.killstorm103.rebug.commands.*
  items:
    description: Opens items menu!
    usage: /<command>
    permissions:
    - me.killstorm103.rebug.command.menu
    - me.killstorm103.rebug.user.menu.items
    - me.killstorm103.rebug.*
    - me.killstorm103.rebug.server_owner
    - me.killstorm103.rebug.server_admin
    - me.killstorm103.rebug.commands.*
  enchant:
    description: Enchant any item you want!
    usage: /<command>
    permissions:
    - me.killstorm103.rebug.command.enchant
    - me.killstorm103.rebug.*
    - me.killstorm103.rebug.server_owner
    - me.killstorm103.rebug.server_admin
    - me.killstorm103.rebug.commands.*
  invsee:
    description: Enchant any item you want!
    usage: /<command>
    permissions:
    - me.killstorm103.rebug.command.invseecmd
    - me.killstorm103.rebug.*
    - me.killstorm103.rebug.server_owner
    - me.killstorm103.rebug.server_admin
    - me.killstorm103.rebug.commands.*
  player:
    description: get info about a player
    usage: /<command>
    permissions:
    - me.killstorm103.rebug.command.playerinfocmd
    - me.killstorm103.rebug.*
    - me.killstorm103.rebug.server_owner
    - me.killstorm103.rebug.server_admin
    - me.killstorm103.rebug.commands.*
  enchantment:
    description: Enchant any item you want!
    usage: /<command>
    permissions:
    - me.killstorm103.rebug.command.enchant
    - me.killstorm103.rebug.*
    - me.killstorm103.rebug.server_owner
    - me.killstorm103.rebug.server_admin
    - me.killstorm103.rebug.commands.*
  healandfeed:
    description: Heal and feed players
    usage: /<command>
    permissions:
    - me.killstorm103.rebug.command.healandfeed
    - me.killstorm103.rebug.*
    - me.killstorm103.rebug.server_owner
    - me.killstorm103.rebug.server_admin
    - me.killstorm103.rebug.commands.*
  health:
    description: Set your health!
    usage: /<command>
    permissions:
    - me.killstorm103.rebug.command.healthcmd
    - me.killstorm103.rebug.*
    - me.killstorm103.rebug.server_owner
    - me.killstorm103.rebug.server_admin
    - me.killstorm103.rebug.commands.*
  nobreak:
    description: Stops items from breaking
    usage: /<command>
    permissions:
    - me.killstorm103.rebug.command.nobreak
    - me.killstorm103.rebug.*
    - me.killstorm103.rebug.server_owner
    - me.killstorm103.rebug.server_admin
    - me.killstorm103.rebug.commands.*
  ac:
    description: Pick what anticheat you wanna test!
    usage: /<command>
    permissions:
    - me.killstorm103.rebug.command.menu
    - me.killstorm103.rebug.user.select_anticheat
    - me.killstorm103.rebug.*
    - me.killstorm103.rebug.server_owner
    - me.killstorm103.rebug.server_admin
    - me.killstorm103.rebug.commands.*
  settings:
    description: Settings for the player and can open Rebug settings from there if you perms!
    usage: /<command>
    permissions:
    - me.killstorm103.rebug.command.menu
    - me.killstorm103.rebug.user.player_settings
    - me.killstorm103.rebug.*
    - me.killstorm103.rebug.server_owner
    - me.killstorm103.rebug.server_admin
    - me.killstorm103.rebug.commands.*
  potions:
    description: Potions Menu
    usage: /<command>
    permissions:
    - me.killstorm103.rebug.command.menu
    - me.killstorm103.rebug.user.select_potions
    - me.killstorm103.rebug.*
    - me.killstorm103.rebug.server_owner
    - me.killstorm103.rebug.server_admin
    - me.killstorm103.rebug.commands.*
  potion:
    description: Change Potion Effect Settings!
    usage: /<command>
    permissions:
    - me.killstorm103.rebug.*
    - me.killstorm103.rebug.server_owner
    - me.killstorm103.rebug.server_admin
    - me.killstorm103.rebug.commands.potion_settings
    - me.killstorm103.rebug.commands.*
  heal:
    description: Heals players
    usage: /<command>
    permissions:
    - me.killstorm103.rebug.command.healcmd
    - me.killstorm103.rebug.*
    - me.killstorm103.rebug.server_owner
    - me.killstorm103.rebug.server_admin
    - me.killstorm103.rebug.commands.*
  feed:
    description: Feeds players
    usage: /<command>
    permissions:
    - me.killstorm103.rebug.command.feedcmd
    - me.killstorm103.rebug.*
    - me.killstorm103.rebug.server_owner
    - me.killstorm103.rebug.server_admin
    - me.killstorm103.rebug.commands.*
  getuuid:
    description: Gets the uuid of players!
    usage: /<command>
    permissions:
    - me.killstorm103.rebug.command.getuuid
    - me.killstorm103.rebug.*
    - me.killstorm103.rebug.server_owner
    - me.killstorm103.rebug.server_admin
    - me.killstorm103.rebug.commands.*
    
    
depend:
- packetevents
- Netherboard