name: Rebug
version: 1.3
main: me.killstorm103.Rebug.Main.Rebug
author: killstorm103
description: helpful plugin
commands:
  rebug:
    description: command prefix for using rebugs commands
    usage: rebug <command>
  client:
    description: Your description
    usage: /<command>
  exploits:
    description: Your description
    usage: /<command>
  crashers:
    description: Your description
    usage: /<command>
  items:
    description: Your description
    usage: /<command>
  enchant:
    description: Your description
    usage: /<command>
  enchantment:
    description: Your description
    usage: /<command>
  settings:
    description: Your description
    usage: /<command>
  heal:
    description: Your description
    usage: /<command>
  feed:
    description: Your description
    usage: /<command>
    
    
depend:
- packetevents
