name: Rebug
version: 1.2
main: me.killstorm103.Rebug.Main.Rebug
author: killstorm103
description: helpful plugin
commands:
  rebug:
    description: command prefix for using rebugs commands
    usage: rebug <command>
    
depend:
- packetevents
