name: Rebug
version: 1.3
main: me.killstorm103.Rebug.Main.Rebug
author: killstorm103
description: helpful plugin
commands:
  rebug:
    description: command prefix for using rebugs commands
    usage: rebug <command>
  client:
    description: Gets the client brand of a player!
    usage: /<command>
  exploits:
    description: Opens exploits menu!
    usage: /<command>
  crashers:
    description: Opens crashers menu!
    usage: /<command>
  items:
    description: Opens items menu!
    usage: /<command>
  enchant:
    description: Enchant any item you want!
    usage: /<command>
  settings:
    description: Settings for the player and can open Rebug settings from there if you perms!
    usage: /<command>
  heal:
    description: Heals players
    usage: /<command>
  feed:
    description: Feeds players
    usage: /<command>
    
    
depend:
- packetevents
